sonar.projectKey=reservas-sillas-cine
sonar.organization=reservas-sillas-cine
sonar.sources=src
sonar.tests=test
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/index.ts,src/services/interfaces/**,src/config/**
